// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.23.4
// source: proto/dummy.proto

package dummy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Can be embedded in Response message since its only used there
type ProtoResponseType int32

const (
	ProtoResponseType_WAN  ProtoResponseType = 0
	ProtoResponseType_TOOH ProtoResponseType = 1
)

// Enum value maps for ProtoResponseType.
var (
	ProtoResponseType_name = map[int32]string{
		0: "WAN",
		1: "TOOH",
	}
	ProtoResponseType_value = map[string]int32{
		"WAN":  0,
		"TOOH": 1,
	}
)

func (x ProtoResponseType) Enum() *ProtoResponseType {
	p := new(ProtoResponseType)
	*p = x
	return p
}

func (x ProtoResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtoResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dummy_proto_enumTypes[0].Descriptor()
}

func (ProtoResponseType) Type() protoreflect.EnumType {
	return &file_proto_dummy_proto_enumTypes[0]
}

func (x ProtoResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtoResponseType.Descriptor instead.
func (ProtoResponseType) EnumDescriptor() ([]byte, []int) {
	return file_proto_dummy_proto_rawDescGZIP(), []int{0}
}

type ProtoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query   string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	DateTag string `protobuf:"bytes,2,opt,name=date_tag,json=dateTag,proto3" json:"date_tag,omitempty"`
}

func (x *ProtoRequest) Reset() {
	*x = ProtoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dummy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoRequest) ProtoMessage() {}

func (x *ProtoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoRequest.ProtoReflect.Descriptor instead.
func (*ProtoRequest) Descriptor() ([]byte, []int) {
	return file_proto_dummy_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ProtoRequest) GetDateTag() string {
	if x != nil {
		return x.DateTag
	}
	return ""
}

type ProtoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title       string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl    string                 `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Date        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Request     string                 `protobuf:"bytes,6,opt,name=request,proto3" json:"request,omitempty"`
	Type        ProtoResponseType      `protobuf:"varint,7,opt,name=type,proto3,enum=proto.ProtoResponseType" json:"type,omitempty"`
}

func (x *ProtoResponse) Reset() {
	*x = ProtoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dummy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoResponse) ProtoMessage() {}

func (x *ProtoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoResponse.ProtoReflect.Descriptor instead.
func (*ProtoResponse) Descriptor() ([]byte, []int) {
	return file_proto_dummy_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProtoResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProtoResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProtoResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *ProtoResponse) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *ProtoResponse) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *ProtoResponse) GetType() ProtoResponseType {
	if x != nil {
		return x.Type
	}
	return ProtoResponseType_WAN
}

type ProtoResponseList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ProtoResponse `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ProtoResponseList) Reset() {
	*x = ProtoResponseList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dummy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoResponseList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoResponseList) ProtoMessage() {}

func (x *ProtoResponseList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoResponseList.ProtoReflect.Descriptor instead.
func (*ProtoResponseList) Descriptor() ([]byte, []int) {
	return file_proto_dummy_proto_rawDescGZIP(), []int{2}
}

func (x *ProtoResponseList) GetItems() []*ProtoResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

type ProtoResponsePage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32              `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Total int32              `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Items *ProtoResponseList `protobuf:"bytes,3,opt,name=items,proto3" json:"items,omitempty"`
}

func (x *ProtoResponsePage) Reset() {
	*x = ProtoResponsePage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_dummy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoResponsePage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoResponsePage) ProtoMessage() {}

func (x *ProtoResponsePage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoResponsePage.ProtoReflect.Descriptor instead.
func (*ProtoResponsePage) Descriptor() ([]byte, []int) {
	return file_proto_dummy_proto_rawDescGZIP(), []int{3}
}

func (x *ProtoResponsePage) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ProtoResponsePage) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ProtoResponsePage) GetItems() *ProtoResponseList {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_dummy_proto protoreflect.FileDescriptor

var file_proto_dummy_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x0c, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x67, 0x22, 0xec, 0x01, 0x0a,
	0x0d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x55, 0x72, 0x6c, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x3f, 0x0a, 0x11, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x2a, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x6f, 0x0a, 0x11,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x61, 0x67,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x2e, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x2a, 0x26, 0x0a,
	0x11, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x57, 0x41, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x54,
	0x4f, 0x4f, 0x48, 0x10, 0x01, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_dummy_proto_rawDescOnce sync.Once
	file_proto_dummy_proto_rawDescData = file_proto_dummy_proto_rawDesc
)

func file_proto_dummy_proto_rawDescGZIP() []byte {
	file_proto_dummy_proto_rawDescOnce.Do(func() {
		file_proto_dummy_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_dummy_proto_rawDescData)
	})
	return file_proto_dummy_proto_rawDescData
}

var file_proto_dummy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_dummy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_dummy_proto_goTypes = []any{
	(ProtoResponseType)(0),        // 0: proto.ProtoResponseType
	(*ProtoRequest)(nil),          // 1: proto.ProtoRequest
	(*ProtoResponse)(nil),         // 2: proto.ProtoResponse
	(*ProtoResponseList)(nil),     // 3: proto.ProtoResponseList
	(*ProtoResponsePage)(nil),     // 4: proto.ProtoResponsePage
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_proto_dummy_proto_depIdxs = []int32{
	5, // 0: proto.ProtoResponse.date:type_name -> google.protobuf.Timestamp
	0, // 1: proto.ProtoResponse.type:type_name -> proto.ProtoResponseType
	2, // 2: proto.ProtoResponseList.items:type_name -> proto.ProtoResponse
	3, // 3: proto.ProtoResponsePage.items:type_name -> proto.ProtoResponseList
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_dummy_proto_init() }
func file_proto_dummy_proto_init() {
	if File_proto_dummy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_dummy_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ProtoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dummy_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ProtoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dummy_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ProtoResponseList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_dummy_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ProtoResponsePage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_dummy_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_dummy_proto_goTypes,
		DependencyIndexes: file_proto_dummy_proto_depIdxs,
		EnumInfos:         file_proto_dummy_proto_enumTypes,
		MessageInfos:      file_proto_dummy_proto_msgTypes,
	}.Build()
	File_proto_dummy_proto = out.File
	file_proto_dummy_proto_rawDesc = nil
	file_proto_dummy_proto_goTypes = nil
	file_proto_dummy_proto_depIdxs = nil
}
